#!/usr/bin/env python3
"""Generate lights.cfg.example / ragdoll.cfg.example from Knobs.Generated.cs.

Ground truth chain: the plugins' own config classes -> gen_knobs.py ->
Knobs.Generated.cs -> this script. Every knob, its shipped default, and the
gen_knobs one-line help, grouped the way the Tune tab groups them.

FORMAT RULE: help text goes on its OWN comment line ABOVE the key — never
inline after the value. (The lights/ragdoll parsers historically did not strip
inline comments; they now do — the StripInlineComment port from the sky's
2026-08-23 fix — but the examples stay inline-comment-free so they parse
correctly on every plugin version ever deployed.)

  python3 tools/plugin-pack/gen_cfg_examples.py [out_dir]
With no argument, writes AcmeLights/lights.cfg.example and
AcmeRagdoll/ragdoll.cfg.example in the repo; with out_dir, writes both files
there instead (the pack verify uses this to regenerate into a TEMP dir and
diff against the tracked copies — verify must never write the tracked tree).
"""
import re, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "AcmeLauncher", "Knobs.Generated.cs")

ROW = re.compile(
    r'new KnobDef\("(?P<plugin>[^"]*)", "(?P<cfg>[^"]*)", "(?P<group>[^"]*)", '
    r'"(?P<name>[^"]*)", KnobType\.(?P<type>\w+), "(?P<default>[^"]*)", '
    r'"(?P<min>[^"]*)", "(?P<max>[^"]*)", "(?P<help>(?:[^"\\]|\\.)*)"\)')

def ascii_clean(t):
    t = (t.replace("\u2014", "-").replace("\u2013", "-").replace("\u2026", "...")
          .replace("\u2019", "'").replace("\u2192", "->").replace("\u00d7", "x")
          .replace("\u2190", "<-").replace("\u2018", "'").replace("\u201c", '"')
          .replace("\u201d", '"'))
    bad = sorted({c for c in t if ord(c) > 127})
    assert not bad, f"non-ASCII left after cleaning: {bad!r}"
    return t

def trim_num(v):
    return v.rstrip("0").rstrip(".") if "." in v else v

def emit(cfg, out_path, live_path):
    rows = [m.groupdict() for m in ROW.finditer(open(SRC, encoding="utf-8").read())
            if m.group("cfg") == cfg]
    if not rows:
        sys.exit(f"no knobs found for cfg '{cfg}' in {SRC}")
    lines = [
        f"# Acme{cfg.capitalize()} tuning -- EXAMPLE FILE. The live file the plugin reads is",
        f"#   {live_path}",
        f"# (first-existing of: the plugin's env override, C:\\Temp\\acdt\\{cfg}.cfg, ~\\.acdt\\{cfg}.cfg).",
        f"# Copy this there (or use zzpatcher's Tune tab / --tune {cfg}.<knob>=<value>).",
        "# The plugin re-reads it once per second -- edits land in-game without a restart.",
        "# Lines are `key = value`; '#' starts a comment line. Values below are the",
        "# shipped defaults. Help lives on the comment line ABOVE each key.",
        "#",
        "# GENERATED by tools/plugin-pack/gen_cfg_examples.py from Knobs.Generated.cs",
        "# (itself generated from the plugin's own config class). Do not hand-maintain.",
    ]
    group = None
    for r in rows:
        if r["group"] != group:
            group = r["group"]
            lines += ["", f"# --- {group} ---"]
        note = []
        if r["min"] and r["max"]:
            note.append(f"[{trim_num(r['min'])}..{trim_num(r['max'])}]")
        help_ = r["help"].replace('\\"', '"').strip()
        if help_:
            note.append(help_)
        if note:
            lines.append("# " + " ".join(note))
        lines.append(f"{r['name']} = {r['default']}")
    text = ascii_clean("\n".join(lines) + "\n")
    with open(out_path, "w", encoding="ascii", newline="\n") as f:
        f.write(text)
    print(f"wrote {out_path} ({len(rows)} knobs)")

out_dir = sys.argv[1] if len(sys.argv) > 1 else None
def dest(plugin, name):
    return os.path.join(out_dir, name) if out_dir else os.path.join(REPO, plugin, name)

emit("lights",  dest("AcmeLights",  "lights.cfg.example"),  r"C:\Temp\acdt\lights.cfg")
emit("ragdoll", dest("AcmeRagdoll", "ragdoll.cfg.example"), r"C:\Temp\acdt\ragdoll.cfg")
