// AUTO-GENERATED by the DeathVariety PCA fit over ragdoll_profiles.json (693 bodies).
// The "death manifold": PCA of the 18 sim params, top-4 principal components.
// Variance explained by these 4 axes: ~0.72 (PC1 looseness/chaos, PC2 directional violence, PC3 settle-duration, PC4 energy).
// Do not edit by hand; regenerate from AcmeRagdoll/tools/fit_deathvariety.py.
namespace AcmeRagdoll.Sim {
    /// <summary>Baked PCA "death manifold" model. 18 params, K=4 principal components.
    /// Std is the per-param standard deviation across the 693 profiles; Basis is the 18x4
    /// eigenvector matrix (row-major, standardized space); Eigen is the 4 eigenvalues (variance
    /// along each PC); Alpha is the R4 generalized-golden-ratio additive-recurrence constant per
    /// PC for the low-discrepancy (blue-noise) latent sequence.</summary>
    internal static class DeathVarietyModel {
        public const int P = 18;   // params
        public const int K = 4;    // principal components

        // canonical parameter order (must match RagdollParams field order used by DeathVariety)
        // impulse, toppleGain, toppleRateCap, twist, dirJitter, linearFrac, jitter, bounceMax, maxSpeed, maxUpSpeed, damping, floorFriction, giveMin, giveSpan, giveRamp, coreBias, fallFrames, dirBiasStrength

        public static readonly float[] Std = new float[P] {
        0.17484519f, 0.14602151f, 0.04451043f, 0.39702869f, 0.11996549f, 0.04724904f, 0.02071747f, 0.03547493f, 0.40042456f, 0.19605943f, 0.00203534f, 0.04083254f, 0.04967171f, 0.08050071f, 0.05255361f, 0.05453398f, 13.09148886f, 0.13499624f
        };

        // 18x4 row-major eigenvector basis (standardized space)
        public static readonly float[] Basis = new float[P * K] {
        0.07862524f, 0.32668014f, -0.05615026f, 0.20461344f,
        -0.00634119f, 0.39804690f, 0.35150867f, -0.12874960f,
        0.22920364f, 0.28981561f, -0.09626073f, -0.13079924f,
        0.21489884f, 0.00363028f, 0.04763109f, 0.23349754f,
        0.37471779f, -0.06289760f, 0.01951928f, -0.01573883f,
        0.02098231f, 0.41079473f, 0.31758984f, -0.14301581f,
        0.34162051f, -0.11616003f, 0.09761239f, 0.07412024f,
        0.19210212f, 0.24527435f, -0.18010094f, -0.04516774f,
        0.02276930f, 0.30492474f, -0.22417445f, 0.47888224f,
        0.05470423f, 0.24359634f, -0.22104986f, 0.50611269f,
        -0.16827689f, -0.14521975f, 0.35979741f, 0.37622782f,
        -0.24265883f, -0.19653475f, 0.06707005f, 0.00804653f,
        -0.34125393f, 0.10607662f, -0.14732819f, -0.00582679f,
        0.35011317f, -0.13522380f, 0.20726253f, 0.14292635f,
        0.36521540f, -0.08686798f, 0.00774747f, -0.06681468f,
        -0.33333557f, 0.19504290f, -0.17766925f, -0.03925426f,
        -0.15984509f, -0.09032093f, 0.45696025f, 0.39878712f,
        -0.02846635f, 0.33038626f, 0.42470332f, -0.17059789f,
        };

        public static readonly float[] Eigen = new float[K] { 5.46380146f, 4.39420278f, 1.71956099f, 1.39694149f };

        // R4 low-discrepancy additive constants (frac(phi^-i), phi^5 = phi + 1)
        public static readonly double[] Alpha = new double[K] { 0.8566748838545029, 0.7338918566271260, 0.6287067210378086, 0.5385972572236100 };
    }
}
