#!/usr/bin/env python3
"""
fix_vanquish_world.py — Complete Vanquish World Fix
=====================================================

Addresses ALL issues found in the spawn location investigation:
  1. Remaps or clears the encounter table (165K retail generator entries)
  2. Reads vanquish client_cell_1.dat to extract terrain heights
  3. Z-snaps all outdoor landblock_instance entries to vanquish terrain
  4. Remaps portal destinations in weenie_properties_position
  5. Generates a complete SQL fix file

Usage:
    python scripts/fix_vanquish_world.py [--dry-run]
"""

import json
import math
import os
import re
import struct
import sys
import time
from collections import defaultdict
from typing import Dict, List, Optional, Set, Tuple

# ─── Configuration ───────────────────────────────────────────────────────────

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Input files
CLUSTERS_JSON = os.path.join(BASE_DIR, "pipeline_data", "population_output", "clusters.json")
VANQUISH_DAT = os.path.join(BASE_DIR, "projects", "vanquishtest", "client_cell_1.dat")
HEIGHT_CACHE_JSON = os.path.join(BASE_DIR, "pipeline_data", "population_output", "vanquish_heights.json")
DIFFICULTY_GRADIENT = os.path.join(BASE_DIR, "pipeline_data", "enrichment", "difficulty_gradient.json")
RETAIL_SQL = r"D:\ACE\world-db\ACE-World-Database-v0.9.292.sql"

# Database
MYSQL = r"C:\Program Files\MariaDB 12.2\bin\mysql.exe"

# Output
OUTPUT_DIR = os.path.join(BASE_DIR, "pipeline_data", "population_output")
OUTPUT_SQL = os.path.join(OUTPUT_DIR, "vanquish_world_fix.sql")

# DAT header offset (AC cell DAT format)
DAT_HEADER_OFFSET = 0x140

# Height scale: each raw byte * 2.0 = world height units
HEIGHT_SCALE = 2.0
# Landblock size in world units
LB_WORLD_SIZE = 192.0
# Height grid: 9x9 per landblock, spacing = 192/8 = 24 units
HEIGHT_GRID_SIZE = 9
HEIGHT_CELL_SIZE = 24.0


# ─── Phase 1: Load LB Remap + Parse Retail Data ──────────────────────────────

LB_REMAP_JSON = os.path.join(OUTPUT_DIR, "lb_remap.json")

def load_lb_remap_and_retail_data():
    """
    Load the existing lb_remap.json (generated by redistribute_clusters.py)
    and parse the retail SQL for instance/link data needed by later phases.
    
    IMPORTANT: This does NOT regenerate lb_remap.json. The remap is the
    authoritative source produced by redistribute_clusters.py. Regenerating
    it here would overwrite the redistributed placement with the old
    clustered one.
    """
    # ── Load existing lb_remap.json ──
    if not os.path.exists(LB_REMAP_JSON):
        raise FileNotFoundError(
            f"lb_remap.json not found at {LB_REMAP_JSON}\n"
            f"Run redistribute_clusters.py first to generate it."
        )

    print(f"  Loading lb_remap from {LB_REMAP_JSON}...")
    with open(LB_REMAP_JSON, 'r') as f:
        remap_dict = json.load(f)

    lb_remap: Dict[Tuple[int, int], Tuple[int, int]] = {}
    for k, v in remap_dict.items():
        ox, oy = [int(x) for x in k.split(',')]
        vx, vy = [int(x) for x in v.split(',')]
        lb_remap[(ox, oy)] = (vx, vy)
    print(f"    Loaded {len(lb_remap)} remap entries")

    # ── Parse retail SQL for instance data ──
    sys.path.insert(0, os.path.join(BASE_DIR, "scripts"))
    import cluster_shuffle_populate as csp

    instances_by_lb, links = csp.parse_retail_sql(RETAIL_SQL)
    interior_instances = instances_by_lb.pop((-1, -1), [])

    clusters = csp.find_clusters(instances_by_lb)

    wcid_types = csp.load_wcid_types()
    csp.classify_clusters(clusters, wcid_types)

    # Load gradient for encounter remap (ocean check)
    gradient = csp.load_difficulty_gradient(DIFFICULTY_GRADIENT)

    return lb_remap, clusters, gradient, instances_by_lb, interior_instances, links, wcid_types


# ─── Phase 2: Load Vanquish Height Cache ──────────────────────────────────────

def load_height_cache() -> Dict[str, List[float]]:
    """
    Load the pre-extracted height cache from vanquish_heights.json.
    Generated by extract_dat_heights.py which scans the cell DAT.
    Keys are "lbX,lbY", values are 81-element float arrays (9x9 grid).
    """
    if not os.path.exists(HEIGHT_CACHE_JSON):
        print(f"    Height cache not found at {HEIGHT_CACHE_JSON}")
        print("    Run: python scripts/extract_dat_heights.py first")
        return {}

    print(f"    Loading {HEIGHT_CACHE_JSON}...")
    with open(HEIGHT_CACHE_JSON, 'r') as f:
        cache = json.load(f)
    print(f"    Loaded heights for {len(cache)} landblocks")
    return cache


def interpolate_height(heights: List[float], local_x: float, local_y: float) -> float:
    """Bilinear interpolation of terrain height at a local position within a landblock."""
    gx = max(0.0, min(8.0, local_x / HEIGHT_CELL_SIZE))
    gy = max(0.0, min(8.0, local_y / HEIGHT_CELL_SIZE))
    ix = min(int(gx), 7)
    iy = min(int(gy), 7)
    fx = gx - ix
    fy = gy - iy

    h00 = heights[iy * 9 + ix]
    h10 = heights[iy * 9 + min(ix + 1, 8)]
    h01 = heights[min(iy + 1, 8) * 9 + ix]
    h11 = heights[min(iy + 1, 8) * 9 + min(ix + 1, 8)]

    return h00 * (1 - fx) * (1 - fy) + h10 * fx * (1 - fy) + \
           h01 * (1 - fx) * fy + h11 * fx * fy


# ─── Phase 3: Generate Complete Fix SQL ───────────────────────────────────────

def generate_encounter_remap_sql(
    lb_remap: Dict[Tuple[int, int], Tuple[int, int]],
    gradient: List[List[int]],
    output_lines: list
) -> Tuple[int, int, int]:
    """Generate SQL to remap the encounter table using cluster offsets."""
    import subprocess

    print("  Querying encounter table...")
    result = subprocess.run(
        [MYSQL, "-u", "root", "-pbaltic", "ace_world",
         "-e", "SELECT id, landblock, weenie_Class_Id, cell_X, cell_Y FROM encounter;",
         "--batch"],
        capture_output=True, text=True, timeout=30
    )

    if result.returncode != 0:
        print(f"    ERROR: {result.stderr[:300]}")
        return 0, 0, 0

    lines = result.stdout.strip().split("\n")
    if len(lines) < 2:
        print("    No encounters found")
        return 0, 0, 0

    headers = lines[0].split("\t")
    total = len(lines) - 1
    remapped = 0
    dropped = 0

    output_lines.append("-- === ENCOUNTER TABLE REMAP ===")
    output_lines.append("-- Clear retail encounters and insert remapped versions")
    output_lines.append("DELETE FROM `encounter`;")
    output_lines.append("")

    batch = []
    batch_size = 500

    for line in lines[1:]:
        parts = line.split("\t")
        if len(parts) < 5:
            continue

        enc_id = int(parts[0])
        landblock = int(parts[1])
        wcid = int(parts[2])
        cell_x = int(parts[3])
        cell_y = int(parts[4])

        # Decode encounter landblock (high byte = lbX, low byte = lbY)
        lbX = (landblock >> 8) & 0xFF
        lbY = landblock & 0xFF

        # Look up remap
        if (lbX, lbY) in lb_remap:
            vx, vy = lb_remap[(lbX, lbY)]
            # Check if target is valid (not ocean)
            if 0 <= vx < 255 and 0 <= vy < 255 and gradient[vy][vx] >= 0:
                new_landblock = (vx << 8) | vy
                batch.append(f"({enc_id},{new_landblock},{wcid},{cell_x},{cell_y},NOW())")
                remapped += 1
            else:
                dropped += 1
        else:
            dropped += 1

        if len(batch) >= batch_size:
            output_lines.append(
                "INSERT INTO `encounter` (`id`, `landblock`, `weenie_Class_Id`, "
                "`cell_X`, `cell_Y`, `last_Modified`) VALUES"
            )
            output_lines.append(",\n".join(batch) + ";")
            output_lines.append("")
            batch = []

    if batch:
        output_lines.append(
            "INSERT INTO `encounter` (`id`, `landblock`, `weenie_Class_Id`, "
            "`cell_X`, `cell_Y`, `last_Modified`) VALUES"
        )
        output_lines.append(",\n".join(batch) + ";")
        output_lines.append("")

    print(f"    Encounters: {total} total, {remapped} remapped, {dropped} dropped")
    return total, remapped, dropped


def generate_z_height_fix_sql(
    height_cache: Dict[str, List[float]],
    output_lines: list
) -> int:
    """Generate SQL UPDATEs to fix Z-heights for outdoor instances."""
    import subprocess

    print("  Querying outdoor instances for Z-fix...")
    result = subprocess.run(
        [MYSQL, "-u", "root", "-pbaltic", "ace_world",
         "-e", "SELECT guid, obj_Cell_Id, origin_X, origin_Y, origin_Z "
               "FROM landblock_instance "
               "WHERE (obj_Cell_Id & 0xFFFF) < 0x100 "
               "AND (obj_Cell_Id >> 24 & 0xFF) > 0;",
         "--batch"],
        capture_output=True, text=True, timeout=60
    )

    if result.returncode != 0:
        print(f"    ERROR: {result.stderr[:300]}")
        return 0

    lines = result.stdout.strip().split("\n")
    if len(lines) < 2:
        print("    No outdoor instances found")
        return 0

    output_lines.append("-- === Z-HEIGHT SNAP (outdoor instances) ===")
    output_lines.append(f"-- Adjusting {len(lines)-1} outdoor instances to vanquish terrain height")
    output_lines.append("")

    fixed = 0
    skipped = 0
    batch = []
    batch_size = 500

    for line in lines[1:]:
        parts = line.split("\t")
        if len(parts) < 5:
            continue

        guid = int(parts[0])
        cell_id = int(parts[1])
        origin_x = float(parts[2])
        origin_y = float(parts[3])
        origin_z = float(parts[4])

        lbX = (cell_id >> 24) & 0xFF
        lbY = (cell_id >> 16) & 0xFF

        key = f"{lbX},{lbY}"
        if key not in height_cache:
            skipped += 1
            continue

        heights = height_cache[key]
        terrain_h = interpolate_height(heights, origin_x, origin_y)

        # Place object slightly above terrain surface
        new_z = round(terrain_h + 0.005, 6)

        if abs(new_z - origin_z) > 0.01:
            batch.append(
                f"UPDATE `landblock_instance` SET `origin_Z` = {new_z} "
                f"WHERE `guid` = {guid};"
            )
            fixed += 1

        if len(batch) >= batch_size:
            output_lines.extend(batch)
            output_lines.append("")
            batch = []

    if batch:
        output_lines.extend(batch)
        output_lines.append("")

    print(f"    Z-fixed: {fixed}, skipped (no height data): {skipped}")
    return fixed


def generate_portal_remap_sql(
    lb_remap: Dict[Tuple[int, int], Tuple[int, int]],
    output_lines: list
) -> int:
    """Generate SQL to remap portal destinations in weenie_properties_position."""
    import subprocess

    print("  Querying portal destinations...")
    result = subprocess.run(
        [MYSQL, "-u", "root", "-pbaltic", "ace_world",
         "-e", "SELECT object_Id, position_Type, obj_Cell_Id, "
               "origin_X, origin_Y, origin_Z "
               "FROM weenie_properties_position;",
         "--batch"],
        capture_output=True, text=True, timeout=30
    )

    if result.returncode != 0:
        print(f"    ERROR: {result.stderr[:300]}")
        return 0

    lines = result.stdout.strip().split("\n")
    if len(lines) < 2:
        return 0

    output_lines.append("-- === PORTAL DESTINATION REMAP ===")
    output_lines.append("-- Remap outdoor portal destinations to vanquish positions")
    output_lines.append("")

    updates = 0
    for line in lines[1:]:
        parts = line.split("\t")
        if len(parts) < 6:
            continue

        obj_id = int(parts[0])
        pos_type = int(parts[1])
        cell_id = int(parts[2])
        origin_x = float(parts[3])
        origin_y = float(parts[4])
        origin_z = float(parts[5])

        cell_idx = cell_id & 0xFFFF
        if cell_idx >= 0x100:
            continue  # interior cell, don't remap

        lbX = (cell_id >> 24) & 0xFF
        lbY = (cell_id >> 16) & 0xFF

        if (lbX, lbY) not in lb_remap:
            continue

        vx, vy = lb_remap[(lbX, lbY)]
        new_cell = (vx << 24) | (vy << 16) | cell_idx

        if new_cell != cell_id:
            output_lines.append(
                f"UPDATE `weenie_properties_position` SET `obj_Cell_Id` = {new_cell} "
                f"WHERE `object_Id` = {obj_id} AND `position_Type` = {pos_type} "
                f"AND `obj_Cell_Id` = {cell_id};"
            )
            updates += 1

    print(f"    Portal destinations remapped: {updates}")
    return updates


# ─── Phase 4: Config.js Fix ──────────────────────────────────────────────────

def fix_config_js(lb_remap: Dict[Tuple[int, int], Tuple[int, int]]):
    """Update Config.js to disable auto-update and fix preloaded landblocks."""
    config_path = r"D:\ACE\Server\Config.js"

    if not os.path.exists(config_path):
        print(f"  Config.js not found at {config_path}")
        return

    print(f"  Updating {config_path}...")

    with open(config_path, 'r') as f:
        content = f.read()

    changes = 0

    # Disable auto-update
    if '"AutoUpdateWorldDatabase": true' in content:
        content = content.replace(
            '"AutoUpdateWorldDatabase": true',
            '"AutoUpdateWorldDatabase": false'
        )
        changes += 1
        print("    Disabled AutoUpdateWorldDatabase")

    # Disable AutoApplyWorldCustomizations (to prevent re-import)
    if '"AutoApplyWorldCustomizations": true' in content:
        content = content.replace(
            '"AutoApplyWorldCustomizations": true',
            '"AutoApplyWorldCustomizations": false'
        )
        changes += 1
        print("    Disabled AutoApplyWorldCustomizations")

    # Remap preloaded landblock IDs
    preload_remaps = {
        # Retail starter towns -> vanquish positions
        "A9B4FFFF": None,  # Holtburg
        "DA55FFFF": None,  # Shoushi
        "7D64FFFF": None,  # Yaraq
    }

    for hex_id, _ in preload_remaps.items():
        lb_val = int(hex_id[:4], 16)
        lbX = (lb_val >> 8) & 0xFF
        lbY = lb_val & 0xFF

        if (lbX, lbY) in lb_remap:
            vx, vy = lb_remap[(lbX, lbY)]
            new_hex = f"{vx:02X}{vy:02X}FFFF"
            preload_remaps[hex_id] = new_hex

    for old_hex, new_hex in preload_remaps.items():
        if new_hex and old_hex in content:
            content = content.replace(old_hex, new_hex)
            changes += 1
            print(f"    Remapped preload {old_hex} -> {new_hex}")

    if changes > 0:
        # Backup original
        backup_path = config_path + ".retail.bak"
        if not os.path.exists(backup_path):
            import shutil
            shutil.copy2(config_path, backup_path)
            print(f"    Backed up original to {backup_path}")

        with open(config_path, 'w') as f:
            f.write(content)
        print(f"    Wrote {changes} changes to Config.js")
    else:
        print("    No changes needed")


# ─── Main ────────────────────────────────────────────────────────────────────

def main():
    dry_run = "--dry-run" in sys.argv
    skip_z = "--skip-z" in sys.argv

    print("=" * 72)
    print("  Vanquish World — Complete Fix")
    print("=" * 72)
    print()

    t0 = time.time()

    # ── Phase 1: Load LB remap + retail data ──
    print("[Phase 1] Loading landblock remap and retail data...")
    lb_remap, clusters, gradient, instances_by_lb, interior_instances, links, wcid_types = \
        load_lb_remap_and_retail_data()
    print()

    # ── Phase 2: Load Vanquish height cache ──
    height_cache = {}
    if not skip_z:
        print("[Phase 2] Loading Vanquish height cache...")
        height_cache = load_height_cache()
        if not height_cache:
            print("    No height data available. Run extract_dat_heights.py first.")
            print("    Continuing without Z-height fix.")
        else:
            # Quick validation
            test_key = "128,128"
            if test_key in height_cache:
                h = height_cache[test_key]
                print(f"    Test LB(128,128): min={min(h):.0f} max={max(h):.0f}")
        print()
    else:
        print("[Phase 2] Skipping Z-height fix (--skip-z)")
        print()

    # ── Phase 3: Generate fix SQL ──
    print("[Phase 3] Generating fix SQL...")
    sql_lines = []
    sql_lines.append("-- ═══════════════════════════════════════════════════════════════════")
    sql_lines.append("-- Vanquish World — Complete Fix")
    sql_lines.append(f"-- Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}")
    sql_lines.append("-- ═══════════════════════════════════════════════════════════════════")
    sql_lines.append("")
    sql_lines.append("USE `ace_world`;")
    sql_lines.append("")

    # 3a: Encounter table
    print()
    enc_total, enc_remapped, enc_dropped = generate_encounter_remap_sql(
        lb_remap, gradient, sql_lines
    )

    # 3b: Portal destinations
    print()
    portal_updates = generate_portal_remap_sql(lb_remap, sql_lines)

    # 3c: Z-height snap
    z_fixed = 0
    if height_cache and not skip_z:
        print()
        z_fixed = generate_z_height_fix_sql(height_cache, sql_lines)

    # Write SQL file
    if not dry_run:
        os.makedirs(OUTPUT_DIR, exist_ok=True)
        with open(OUTPUT_SQL, 'w', encoding='utf-8') as f:
            f.write("\n".join(sql_lines))
        size_mb = os.path.getsize(OUTPUT_SQL) / 1024 / 1024
        print(f"\n    Written to {OUTPUT_SQL} ({size_mb:.1f} MB)")

    # ── Phase 4: Config.js ──
    print()
    print("[Phase 4] Fixing Config.js...")
    if not dry_run:
        fix_config_js(lb_remap)
    else:
        print("    [DRY RUN] Skipped")

    # ── Summary ──
    elapsed = time.time() - t0
    print()
    print("=" * 72)
    print("  Summary")
    print("=" * 72)
    print(f"  Encounters: {enc_total} total, {enc_remapped} remapped, {enc_dropped} dropped")
    print(f"  Portal destinations remapped: {portal_updates}")
    print(f"  Z-heights fixed: {z_fixed}")
    print(f"  LB remap entries: {len(lb_remap)}")
    print(f"  Time: {elapsed:.1f}s")
    print()

    if dry_run:
        print("  *** DRY RUN — no files written ***")
    else:
        print("  Output files:")
        print(f"    1. {OUTPUT_SQL}")
        print(f"    2. Config.js (updated in place)")
        print()
        print("  To apply the SQL fix:")
        print(f'    & "{MYSQL}" -u root -pbaltic ace_world < "{OUTPUT_SQL}"')
        print()
        print("  Then restart ACE server for changes to take effect.")

    print()
    print("Done!")


if __name__ == '__main__':
    main()
