using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using SixLabors.ImageSharp.Processing;
using DRW = DatReaderWriter;

namespace WorldBuilder.Terminal;

/// <summary>
/// UI workspace suite — the headless port of the two community desktop
/// tools studied 2026-07-02 (`AC_UI_Asset_Builder` v0.3, Rust/egui, and
/// `Asherons_Interface` v0.1, WPF/DatReaderWriter 2.1.6; sources under
/// /mnt/wbterminal2/asheron-ui-tools/ incl. ILSpy decompile in decomp/).
/// Five commands over the retail UI stack in the DATs:
///
///   - <c>ui-layout-list</c> — enumerate every LayoutDesc in the local
///     DAT with dims/element/image counts + resolved root names (the
///     Asherons-Interface layout dropdown, headless).
///
///   - <c>ui-layout-render</c> — compose a LayoutDesc to a PNG the way
///     the retail client would draw it: base-element inheritance chains
///     (BaseLayoutId/BaseElement), per-state media with the retail
///     fallback order (requested → Normal → default StateDesc), images
///     tiled at native size (the reference app's TileMode=Tile,
///     absolute-viewport behaviour), MediaDescAlpha masks multiplied
///     into the RGBA, MediaDescAnimation frame selection, and text drawn
///     with the RETAIL BITMAP FONTS (DBObjs.Font glyph atlas +
///     StringTable strings from client_local_English) honouring the
///     UICore_Text_* colour/justification/margin properties. Emits a
///     JSON render manifest alongside (what drew, what was skipped).
///
///   - <c>ui-element-edit</c> — the Asherons-Interface move/resize
///     workflow, headless: patch ElementDesc X/Y/Width/Height/ZLevel in
///     a LayoutDesc and write it back with TryWriteFile. Writes are
///     REFUSED against ~/ac_base_dats — point it at a copy.
///
///   - <c>ui-image-replace</c> — the Asset-Builder "Save to DAT" path:
///     PNG → RenderSurface (format preserved for R8G8B8/A8R8G8B8
///     originals, everything else re-encoded A8R8G8B8) written into a
///     portal-DAT copy. Batch via explicit pairs or a directory of
///     0x06XXXXXX.png files (the tools' baked/images convention).
///
///   - <c>ui-pack-export</c> — emit an AC_UI_Asset_Builder-compatible
///     <c>reference_pack.json</c> (BakedReferencePack version 1: panels
///     → flattened nodes with traversal indices, widget kinds, state
///     image sets; images[] usage cross-reference) + images/ PNGs, so
///     the community tool can open a workspace generated by us.
///
/// Property-ID constants and the justification/state fallback semantics
/// were lifted from the decompiled reference app (MainWindow.cs) and the
/// retail MasterPropertyId table it embeds; the pack schema field names
/// come from the Rust exe's serde struct strings (BakedReferencePack /
/// BakedImageEntry / BakedNodeUsage / BakedSkippedPanel).
/// </summary>
public partial class CommandEngine {

    // ─────────────────────────────────────────────────────────────────
    //  Retail UICore_Text_* master-property ids (MainWindow.cs enum).
    // ─────────────────────────────────────────────────────────────────
    private const uint MPID_Text_HJustify   = 20;
    private const uint MPID_Text_VJustify   = 21;
    private const uint MPID_Text_Entry      = 23;
    private const uint MPID_Text_Font       = 24;
    private const uint MPID_Text_FontColor  = 25;
    private const uint MPID_Text_Fonts      = 26;
    private const uint MPID_Text_FontColors = 27;
    private const uint MPID_Text_LeftMargin = 35;
    private const uint MPID_Text_RightMargin = 36;
    private const uint MPID_Text_TopMargin  = 37;
    private const uint MPID_Text_BottomMargin = 38;

    // ─────────────────────────────────────────────────────────────────
    //  Result records
    // ─────────────────────────────────────────────────────────────────

    public sealed record UiLayoutListEntry(
        string LayoutIdHex, uint LayoutId, uint Width, uint Height,
        int RootCount, int ElementCount, int ImageDidCount,
        string? RootElementIdName);

    public sealed record UiLayoutListResult(
        string DatPath, int Count, IReadOnlyList<UiLayoutListEntry> Layouts);

    public sealed record UiRenderedElement(
        string ElementIdHex, string? ElementIdName, int AbsX, int AbsY,
        uint Width, uint Height, string StateUsed,
        IReadOnlyList<string> ImagesDrawn,
        string? TextDrawn, string? FontIdHex,
        IReadOnlyList<string> MediaSkipped,
        int InheritanceDepth);

    public sealed record UiLayoutRenderResult(
        string LayoutIdHex, uint Width, uint Height, int Scale,
        string PngPath, string? ManifestPath, int ElementsDrawn,
        int ImagesDrawn, int TextRuns, int AnimationsSeen,
        IReadOnlyList<string> Warnings,
        IReadOnlyList<UiRenderedElement> Elements);

    public sealed record UiElementEditResult(
        string DatPath, string LayoutIdHex, bool DryRun, bool Written,
        IReadOnlyList<Dictionary<string, object?>> Edits);

    public sealed record UiImageReplaceResult(
        string DatPath, bool DryRun, int RequestedCount, int WrittenCount,
        int FailCount, IReadOnlyList<Dictionary<string, object?>> Records);

    public sealed record UiPackExportResult(
        string OutDir, string PackJsonPath, int PanelCount, int NodeCount,
        int ImageCount, int PngPass, int PngFail, string? ImagesDir);

    // ─────────────────────────────────────────────────────────────────
    //  ui-layout-list
    // ─────────────────────────────────────────────────────────────────

    public UiLayoutListResult UiLayoutList(string? datPath) {
        using var collection = OpenUiCollectionRead(datPath);
        var localPath = ResolveDatPathOrAlias(datPath, defaultAlias: "local");

        var entries = new List<UiLayoutListEntry>();
        foreach (var id in collection.Local.GetAllIdsOfType<DRW.DBObjs.LayoutDesc>().OrderBy(i => i)) {
            if (!collection.TryGet<DRW.DBObjs.LayoutDesc>(id, out var layout) || layout == null) continue;

            int total = 0;
            var dids = new SortedSet<uint>();
            void Walk(DRW.Types.ElementDesc el) {
                total++;
                CollectStateDids(el.StateDesc, dids);
                if (el.States != null) {
                    foreach (var s in el.States.Values) CollectStateDids(s, dids);
                }
                if (el.Children != null) {
                    foreach (var c in el.Children.Values) Walk(c);
                }
            }
            foreach (var root in layout.Elements.Values) Walk(root);

            var firstRoot = layout.Elements.Values
                .OrderBy(e => e.ReadOrder).FirstOrDefault();
            entries.Add(new UiLayoutListEntry(
                LayoutIdHex: $"0x{id:X8}",
                LayoutId: id,
                Width: layout.Width,
                Height: layout.Height,
                RootCount: layout.Elements.Count,
                ElementCount: total,
                ImageDidCount: dids.Count,
                RootElementIdName: firstRoot != null
                    ? TryResolveUiElementIdName(firstRoot.ElementId) : null));
        }
        return new UiLayoutListResult(localPath, entries.Count, entries);
    }

    /// <summary>Collect image DIDs referenced by one StateDesc — both the
    /// media list and any DID-shaped property value (same window the
    /// dump command uses).</summary>
    private static void CollectStateDids(DRW.Types.StateDesc? state, SortedSet<uint> sink) {
        if (state == null) return;
        if (state.Media != null) {
            foreach (var m in state.Media) {
                foreach (var f in m.GetType().GetFields(
                    System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance)) {
                    CollectImageDidsFromValue(f.GetValue(m), sink);
                }
            }
        }
        if (state.Properties != null) {
            foreach (var kvp in state.Properties) {
                var valueField = kvp.Value.GetType().GetField("Value");
                var maybe = ExtractMaybeUint(valueField?.GetValue(kvp.Value));
                if (maybe.HasValue && IsImageDid(maybe.Value)) sink.Add(maybe.Value);
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────
    //  ui-layout-render
    // ─────────────────────────────────────────────────────────────────

    private sealed class UiRenderContext {
        public required DRW.DatCollection Collection;
        public required Image<Rgba32> Canvas;
        public required Dictionary<uint, (byte[] Rgba, int W, int H)> SurfaceCache;
        public required Dictionary<uint, DRW.DBObjs.Palette> PaletteCache;
        public required List<UiRenderedElement> Drawn;
        public required List<string> Warnings;
        public string? RequestedState;
        public int AnimationFrame;
        public bool DrawText;
        public bool Annotate;
        public int ImagesDrawn;
        public int TextRuns;
        public int AnimationsSeen;
        public List<(int X, int Y, int W, int H)> AnnotateRects = new();
        public uint? DefaultFontId;   // lazily computed most-used font DID
    }

    /// <summary>Text-relevant properties inherited from ancestors whose
    /// StateDesc sets PassToChildren — the retail mechanism that lets a
    /// panel set the font once for all its labels.</summary>
    private readonly record struct UiInheritedText(
        uint FontId,
        (byte R, byte G, byte B, byte A)? Color,
        uint HJust, uint VJust);

    public UiLayoutRenderResult UiLayoutRender(
        uint layoutId, string outPath, string? datPath,
        string? state, int scale, bool annotate, bool drawText,
        string? background, int animationFrame, string? manifestPath) {

        if (string.IsNullOrWhiteSpace(outPath)) {
            throw new ArgumentException("outPath is required (png destination).");
        }
        if (scale < 1 || scale > 8) {
            throw new ArgumentException("scale must be 1..8.");
        }

        using var collection = OpenUiCollectionRead(datPath);
        if (!collection.TryGet<DRW.DBObjs.LayoutDesc>(layoutId, out var layout) || layout == null) {
            throw new InvalidOperationException($"LayoutDesc 0x{layoutId:X8} not found.");
        }

        int cw = (int)Math.Max(1u, layout.Width);
        int ch = (int)Math.Max(1u, layout.Height);
        var bg = ParseBackground(background);
        var canvas = new Image<Rgba32>(cw, ch, bg);

        var ctx = new UiRenderContext {
            Collection = collection,
            Canvas = canvas,
            SurfaceCache = new Dictionary<uint, (byte[], int, int)>(),
            PaletteCache = new Dictionary<uint, DRW.DBObjs.Palette>(),
            Drawn = new List<UiRenderedElement>(),
            Warnings = new List<string>(),
            RequestedState = string.IsNullOrWhiteSpace(state) ? null : state.Trim(),
            AnimationFrame = animationFrame,
            DrawText = drawText,
            Annotate = annotate,
        };

        foreach (var root in SiblingsInDrawOrder(layout.Elements.Values)) {
            RenderElement(ctx, layout, root, parentAbsX: 0, parentAbsY: 0,
                inherited: new UiInheritedText(0, null, 0, 0));
        }

        if (annotate) {
            foreach (var r in ctx.AnnotateRects) {
                DrawRectOutline(canvas, r.X, r.Y, r.W, r.H, new Rgba32(64, 128, 255, 200));
            }
        }

        if (scale > 1) {
            canvas.Mutate(x => x.Resize(cw * scale, ch * scale, KnownResamplers.NearestNeighbor));
        }

        var outDir = Path.GetDirectoryName(Path.GetFullPath(outPath));
        if (!string.IsNullOrEmpty(outDir)) Directory.CreateDirectory(outDir);
        using (var fs = File.Create(outPath)) {
            canvas.SaveAsPng(fs);
        }
        canvas.Dispose();

        var result = new UiLayoutRenderResult(
            LayoutIdHex: $"0x{layoutId:X8}",
            Width: layout.Width, Height: layout.Height, Scale: scale,
            PngPath: Path.GetFullPath(outPath),
            ManifestPath: manifestPath,
            ElementsDrawn: ctx.Drawn.Count,
            ImagesDrawn: ctx.ImagesDrawn,
            TextRuns: ctx.TextRuns,
            AnimationsSeen: ctx.AnimationsSeen,
            Warnings: ctx.Warnings,
            Elements: ctx.Drawn);

        if (!string.IsNullOrWhiteSpace(manifestPath)) {
            var mDir = Path.GetDirectoryName(Path.GetFullPath(manifestPath));
            if (!string.IsNullOrEmpty(mDir)) Directory.CreateDirectory(mDir);
            File.WriteAllText(manifestPath, JsonSerializer.Serialize(result,
                new JsonSerializerOptions {
                    WriteIndented = true,
                    PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                }));
        }
        return result;
    }

    /// <summary>Sibling draw order — ZLevel ascending, then ReadOrder.
    /// Mirrors the reference app's nested-canvas z-index stacking
    /// (ZLevel/2 within each parent canvas).</summary>
    private static IEnumerable<DRW.Types.ElementDesc> SiblingsInDrawOrder(
        IEnumerable<DRW.Types.ElementDesc> siblings)
        => siblings.OrderBy(e => e.ZLevel).ThenBy(e => e.ReadOrder).ThenBy(e => e.ElementId);

    private void RenderElement(
        UiRenderContext ctx, DRW.DBObjs.LayoutDesc layout,
        DRW.Types.ElementDesc element, int parentAbsX, int parentAbsY,
        UiInheritedText inherited) {

        int absX = parentAbsX + (int)element.X;
        int absY = parentAbsY + (int)element.Y;

        // Base-element inheritance: walk BaseLayoutId/BaseElement up the
        // chain (HandleStates port), composing base-most first. Cycle-
        // and depth-guarded; missing bases degrade to the local element.
        var chain = new List<DRW.Types.ElementDesc>();
        var cur = element;
        var visited = new HashSet<(uint, uint)>();
        while (cur != null) {
            chain.Insert(0, cur);
            if (cur.BaseElement == 0) break;
            if (!visited.Add((cur.BaseLayoutId, cur.BaseElement))) {
                ctx.Warnings.Add($"0x{element.ElementId:X8}: base-element cycle detected; stopping chain walk.");
                break;
            }
            if (chain.Count > 8) {
                ctx.Warnings.Add($"0x{element.ElementId:X8}: base chain deeper than 8; truncated.");
                break;
            }
            if (!ctx.Collection.TryGet<DRW.DBObjs.LayoutDesc>(cur.BaseLayoutId, out var baseLayout)
                || baseLayout == null
                || !baseLayout.Elements.TryGetValue(cur.BaseElement, out var baseEl)
                || baseEl == null) {
                ctx.Warnings.Add($"0x{element.ElementId:X8}: base 0x{cur.BaseLayoutId:X8}/0x{cur.BaseElement:X8} not found.");
                break;
            }
            cur = baseEl;
        }

        var imagesDrawn = new List<string>();
        var mediaSkipped = new List<string>();
        string? textDrawn = null;
        string? fontIdHex = null;
        string stateUsed = "default";

        int w = (int)Math.Max(element.Width, 1u);
        int h = (int)Math.Max(element.Height, 1u);

        foreach (var item in chain) {
            // Default StateDesc media always composes first (the app's
            // HandleStates draws CreateImage(item.StateDesc) then states).
            DrawStateMedia(ctx, item.StateDesc, absX, absY, w, h, imagesDrawn, mediaSkipped);

            // Then the selected state: explicit request, else the
            // element's DefaultState when it exists in the dict, else
            // Normal (SetState's fallback order, headless).
            var pick = PickState(item, ctx.RequestedState, out var pickName);
            if (pick != null) {
                stateUsed = pickName;
                DrawStateMedia(ctx, pick, absX, absY, w, h, imagesDrawn, mediaSkipped);
            }
        }

        // Text-relevant properties — gather from the chain (base-most
        // first so derived overrides win), then fall back to what
        // PassToChildren ancestors handed down, then to the most-used
        // font in the whole local DAT (data-driven default).
        uint localFont = 0;
        (byte R, byte G, byte B, byte A)? localColor = null;
        uint localHJust = 0, localVJust = 0;
        bool passToChildren = false;
        foreach (var item in chain) {
            var sd = item.StateDesc;
            if (sd == null) continue;
            if (sd.PassToChildren) passToChildren = true;
            foreach (var did in EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_Fonts))) {
                if (did != 0) { localFont = did; break; }
            }
            if (localFont == 0) {
                var single = EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_Font)).FirstOrDefault();
                if (single != 0) localFont = single;
            }
            foreach (var c in EnumeratePropertyColors(GetUiProperty(sd, MPID_Text_FontColors))) localColor = c;
            foreach (var c in EnumeratePropertyColors(GetUiProperty(sd, MPID_Text_FontColor))) localColor ??= c;
            var hj = EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_HJustify)).FirstOrDefault();
            if (hj != 0) localHJust = hj;
            var vj = EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_VJustify)).FirstOrDefault();
            if (vj != 0) localVJust = vj;
        }
        var effective = new UiInheritedText(
            FontId: localFont != 0 ? localFont : inherited.FontId,
            Color: localColor ?? inherited.Color,
            HJust: localHJust != 0 ? localHJust : inherited.HJust,
            VJust: localVJust != 0 ? localVJust : inherited.VJust);

        if (ctx.DrawText) {
            foreach (var item in Enumerable.Reverse(chain)) {
                var drawn = TryDrawElementText(ctx, item, absX, absY, w, h, effective, out var usedFont);
                if (drawn != null) {
                    textDrawn = drawn;
                    fontIdHex = usedFont;
                    ctx.TextRuns++;
                    break;
                }
            }
        }

        if (ctx.Annotate) ctx.AnnotateRects.Add((absX, absY, w, h));

        ctx.Drawn.Add(new UiRenderedElement(
            ElementIdHex: $"0x{element.ElementId:X8}",
            ElementIdName: TryResolveUiElementIdName(element.ElementId),
            AbsX: absX, AbsY: absY,
            Width: element.Width, Height: element.Height,
            StateUsed: stateUsed,
            ImagesDrawn: imagesDrawn,
            TextDrawn: textDrawn,
            FontIdHex: fontIdHex,
            MediaSkipped: mediaSkipped,
            InheritanceDepth: chain.Count - 1));

        // PassToChildren propagates this element's text properties to its
        // subtree; otherwise pass through whatever we inherited.
        var childInherited = passToChildren ? effective : inherited;
        if (element.Children != null) {
            foreach (var child in SiblingsInDrawOrder(element.Children.Values)) {
                RenderElement(ctx, layout, child, absX, absY, childInherited);
            }
        }
    }

    /// <summary>Requested state (by UIStateId name or number) → element
    /// DefaultState → Normal. Null when nothing beyond the default
    /// StateDesc applies.</summary>
    private static DRW.Types.StateDesc? PickState(
        DRW.Types.ElementDesc element, string? requested, out string pickedName) {
        pickedName = "default";
        if (element.States == null || element.States.Count == 0) return null;

        if (!string.IsNullOrEmpty(requested)) {
            foreach (var kvp in element.States) {
                var keyName = kvp.Key.ToString();
                if (string.Equals(keyName, requested, StringComparison.OrdinalIgnoreCase)
                    || (uint.TryParse(requested.Replace("0x", ""),
                            System.Globalization.NumberStyles.HexNumber, null, out var reqNum)
                        && (uint)kvp.Key == reqNum)) {
                    pickedName = keyName;
                    return kvp.Value;
                }
            }
        }
        if (element.States.TryGetValue(element.DefaultState, out var defState)) {
            pickedName = element.DefaultState.ToString();
            return defState;
        }
        if (element.States.TryGetValue(DRW.Enums.UIStateId.Normal, out var normal)) {
            pickedName = "Normal";
            return normal;
        }
        return null;
    }

    private void DrawStateMedia(
        UiRenderContext ctx, DRW.Types.StateDesc? state,
        int absX, int absY, int w, int h,
        List<string> imagesDrawn, List<string> mediaSkipped) {
        if (state?.Media == null) return;

        // An Alpha media in the same state masks the Image media drawn
        // with it (the Rust pack pairs image_id + alpha_image_id the
        // same way).
        uint alphaDid = 0;
        foreach (var m in state.Media) {
            if (m is DRW.Types.MediaDescAlpha a) alphaDid = a.File;
        }

        foreach (var m in state.Media) {
            switch (m) {
                case DRW.Types.MediaDescImage img: {
                    if (img.File == 0) break;   // empty media slot, not an error
                    if (TryGetSurfaceRgba(ctx, img.File, out var s)) {
                        BlitTiled(ctx.Canvas, s.Rgba, s.W, s.H, absX, absY, w, h,
                            MaybeAlphaMask(ctx, alphaDid));
                        imagesDrawn.Add($"0x{img.File:X8}");
                        ctx.ImagesDrawn++;
                    } else {
                        ctx.Warnings.Add($"RenderSurface 0x{img.File:X8} failed to decode.");
                    }
                    break;
                }
                case DRW.Types.MediaDescAnimation anim: {
                    ctx.AnimationsSeen++;
                    var frames = GetAnimationFrames(anim);
                    if (frames.Count > 0) {
                        var did = frames[Math.Abs(ctx.AnimationFrame) % frames.Count];
                        if (TryGetSurfaceRgba(ctx, did, out var s)) {
                            BlitTiled(ctx.Canvas, s.Rgba, s.W, s.H, absX, absY, w, h,
                                MaybeAlphaMask(ctx, alphaDid));
                            imagesDrawn.Add($"0x{did:X8} (anim {frames.Count}f)");
                            ctx.ImagesDrawn++;
                        }
                    }
                    break;
                }
                case DRW.Types.MediaDescAlpha:
                    break; // consumed above as the mask
                default:
                    mediaSkipped.Add(m.GetType().Name.Replace("MediaDesc", ""));
                    break;
            }
        }
    }

    /// <summary>MediaDescAnimation.Frames via reflection — the field is a
    /// List&lt;uint&gt; in 2.1.x but its exact name is version-sensitive.</summary>
    private static List<uint> GetAnimationFrames(DRW.Types.MediaDescAnimation anim) {
        var result = new List<uint>();
        foreach (var f in anim.GetType().GetFields(
            System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance)) {
            if (f.GetValue(anim) is IEnumerable<uint> list) {
                result.AddRange(list);
            }
        }
        return result;
    }

    private (byte[] Rgba, int W, int H)? MaybeAlphaMask(UiRenderContext ctx, uint alphaDid) {
        if (alphaDid == 0) return null;
        return TryGetSurfaceRgba(ctx, alphaDid, out var s) ? s : null;
    }

    private bool TryGetSurfaceRgba(UiRenderContext ctx, uint did, out (byte[] Rgba, int W, int H) result) {
        if (ctx.SurfaceCache.TryGetValue(did, out result)) return result.Rgba.Length > 0;
        try {
            if (!ctx.Collection.TryGet<DRW.DBObjs.RenderSurface>(did, out var rs) || rs == null) {
                result = (Array.Empty<byte>(), 0, 0);
                ctx.SurfaceCache[did] = result;
                return false;
            }
            var rgba = DecodeUiRenderSurfaceToRgba8(rs, ctx.Collection.Portal, ctx.PaletteCache, out int w, out int h);
            result = (rgba, w, h);
            ctx.SurfaceCache[did] = result;
            return true;
        } catch (Exception ex) {
            ctx.Warnings.Add($"decode 0x{did:X8}: {ex.Message}");
            result = (Array.Empty<byte>(), 0, 0);
            ctx.SurfaceCache[did] = result;
            return false;
        }
    }

    /// <summary>Tile <paramref name="src"/> at native size across the
    /// destination rect (retail/WPF absolute-viewport Tile semantics),
    /// alpha-compositing src-over. Optional alpha-mask surface is
    /// sampled in the same tiled space; its red channel multiplies the
    /// source alpha (retail alpha masks are grey/A8 surfaces).</summary>
    private static void BlitTiled(
        Image<Rgba32> dst, byte[] src, int sw, int sh,
        int dx, int dy, int dw, int dh,
        (byte[] Rgba, int W, int H)? alphaMask) {
        if (sw <= 0 || sh <= 0) return;
        int x0 = Math.Max(dx, 0), y0 = Math.Max(dy, 0);
        int x1 = Math.Min(dx + dw, dst.Width), y1 = Math.Min(dy + dh, dst.Height);
        for (int y = y0; y < y1; y++) {
            int sy = (y - dy) % sh;
            for (int x = x0; x < x1; x++) {
                int sx = (x - dx) % sw;
                int si = (sy * sw + sx) * 4;
                byte sr = src[si], sg = src[si + 1], sb = src[si + 2], sa = src[si + 3];
                if (alphaMask.HasValue && alphaMask.Value.W > 0) {
                    var (mData, mw, mh) = alphaMask.Value;
                    int mi = (((y - dy) % mh) * mw + ((x - dx) % mw)) * 4;
                    sa = (byte)(sa * mData[mi] / 255);
                }
                if (sa == 0) continue;
                var d = dst[x, y];
                if (sa == 255) {
                    dst[x, y] = new Rgba32(sr, sg, sb, 255);
                } else {
                    int ia = 255 - sa;
                    dst[x, y] = new Rgba32(
                        (byte)((sr * sa + d.R * ia) / 255),
                        (byte)((sg * sa + d.G * ia) / 255),
                        (byte)((sb * sa + d.B * ia) / 255),
                        (byte)Math.Min(255, sa + d.A * ia / 255));
                }
            }
        }
    }

    private static void DrawRectOutline(Image<Rgba32> img, int x, int y, int w, int h, Rgba32 color) {
        int x1 = Math.Min(x + w - 1, img.Width - 1), y1 = Math.Min(y + h - 1, img.Height - 1);
        int cx0 = Math.Max(x, 0), cy0 = Math.Max(y, 0);
        if (cx0 > x1 || cy0 > y1) return;
        for (int i = cx0; i <= x1; i++) {
            if (y >= 0 && y < img.Height) img[i, y] = color;
            if (y1 >= 0 && y1 < img.Height) img[i, y1] = color;
        }
        for (int j = cy0; j <= y1; j++) {
            if (x >= 0 && x < img.Width) img[x, j] = color;
            if (x1 >= 0 && x1 < img.Width) img[x1, j] = color;
        }
    }

    private static Rgba32 ParseBackground(string? background) {
        if (string.IsNullOrWhiteSpace(background) || background.Trim().ToLowerInvariant() == "transparent") {
            return new Rgba32(0, 0, 0, 0);
        }
        var s = background.Trim().TrimStart('#');
        if (s.Length != 6 && s.Length != 8) {
            throw new ArgumentException("background must be 'transparent', #RRGGBB or #RRGGBBAA.");
        }
        byte P(int i) => Convert.ToByte(s.Substring(i, 2), 16);
        return new Rgba32(P(0), P(2), P(4), s.Length == 8 ? P(6) : (byte)255);
    }

    // ── Retail bitmap-font text ──────────────────────────────────────

    private string? TryDrawElementText(
        UiRenderContext ctx, DRW.Types.ElementDesc element,
        int absX, int absY, int w, int h, UiInheritedText effective,
        out string? fontIdHex) {
        fontIdHex = null;
        var state = element.StateDesc;
        if (state?.Properties == null) return null;

        // UICore_Text_entry — StringInfo → StringTable in the local DAT.
        var entry = GetUiProperty(state, MPID_Text_Entry);
        string? text = ResolveStringInfoProperty(ctx, entry);
        if (string.IsNullOrEmpty(text)) return null;

        // Font: chain/inherited (PassToChildren) first, then the
        // most-used font across the local DAT as the data-driven default
        // (the reference app drew nothing here and logged "Font is null!").
        uint fontId = effective.FontId;
        if (fontId == 0) {
            fontId = GetDefaultFontId(ctx);
        }
        if (fontId == 0) {
            ctx.Warnings.Add($"0x{element.ElementId:X8}: text '{Truncate(text, 24)}' has no font (own, inherited or default); skipped.");
            return null;
        }

        if (!ctx.Collection.TryGet<DRW.DBObjs.Font>(fontId, out var font) || font == null) {
            ctx.Warnings.Add($"0x{element.ElementId:X8}: Font 0x{fontId:X8} not found.");
            return null;
        }
        if (!TryGetSurfaceRgba(ctx, font.ForegroundSurfaceDataId, out var atlas)) {
            ctx.Warnings.Add($"0x{element.ElementId:X8}: font atlas 0x{font.ForegroundSurfaceDataId:X8} failed.");
            return null;
        }

        var tint = effective.Color;
        uint hJust = effective.HJust;
        uint vJust = effective.VJust;
        int mLeft = (int)EnumeratePropertyUints(GetUiProperty(state, MPID_Text_LeftMargin)).FirstOrDefault();
        int mRight = (int)EnumeratePropertyUints(GetUiProperty(state, MPID_Text_RightMargin)).FirstOrDefault();
        int mTop = (int)EnumeratePropertyUints(GetUiProperty(state, MPID_Text_TopMargin)).FirstOrDefault();
        int mBottom = (int)EnumeratePropertyUints(GetUiProperty(state, MPID_Text_BottomMargin)).FirstOrDefault();

        var glyphs = font.CharDescs.GroupBy(c => (char)c.Unicode)
            .ToDictionary(g => g.Key, g => g.First());

        // Single-line measurement (multi-line splits on \n).
        var lines = text.Split('\n');
        int lineHeight = (int)Math.Max(font.MaxCharHeight, 1u);
        int totalTextH = lineHeight * lines.Length;
        int yBase = vJust switch {
            4 => absY + mTop,                                    // Top
            5 => absY + h - totalTextH - mBottom,                // Bottom
            _ => absY + Math.Max(0, (h - totalTextH) / 2),       // Center (1/default)
        };

        foreach (var line in lines) {
            int lineW = 0;
            foreach (var chn in line) {
                if (glyphs.TryGetValue(chn, out var g)) {
                    lineW += g.HorizontalOffsetBefore + g.Width + g.HorizontalOffsetAfter;
                }
            }
            int penX = hJust switch {
                2 => absX + mLeft,                               // Left
                3 => absX + w - lineW - mRight,                  // Right
                1 => absX + Math.Max(0, (w - lineW) / 2),        // Center
                _ => absX + mLeft,                               // default Left
            };
            foreach (var chn in line) {
                if (!glyphs.TryGetValue(chn, out var g)) continue;
                penX += g.HorizontalOffsetBefore;
                BlitGlyph(ctx.Canvas, atlas.Rgba, atlas.W, atlas.H,
                    g.OffsetX, g.OffsetY, g.Width, g.Height,
                    penX, yBase + g.VerticalOffsetBefore, tint);
                penX += g.Width + g.HorizontalOffsetAfter;
            }
            yBase += lineHeight;
        }

        fontIdHex = $"0x{fontId:X8}";
        return text;
    }

    private static void BlitGlyph(
        Image<Rgba32> dst, byte[] atlas, int aw, int ah,
        int srcX, int srcY, int gw, int gh, int dx, int dy,
        (byte R, byte G, byte B, byte A)? tint) {
        for (int y = 0; y < gh; y++) {
            int py = dy + y;
            int sy = srcY + y;
            if (py < 0 || py >= dst.Height || sy < 0 || sy >= ah) continue;
            for (int x = 0; x < gw; x++) {
                int px = dx + x;
                int sx = srcX + x;
                if (px < 0 || px >= dst.Width || sx < 0 || sx >= aw) continue;
                int si = (sy * aw + sx) * 4;
                byte sr = atlas[si], sg = atlas[si + 1], sb = atlas[si + 2], sa = atlas[si + 3];
                // Retail glyph atlases are luminance-keyed — treat black
                // as transparent when the surface has no real alpha.
                if (sa == 255 && sr == 0 && sg == 0 && sb == 0) continue;
                byte lum = (byte)((sr * 30 + sg * 59 + sb * 11) / 100);
                byte outA = (byte)(sa == 255 ? lum : (sa * lum / 255));
                if (tint.HasValue) {
                    sr = (byte)(tint.Value.R);
                    sg = (byte)(tint.Value.G);
                    sb = (byte)(tint.Value.B);
                    if (tint.Value.A > 0) outA = (byte)(outA * tint.Value.A / 255);
                } else {
                    sr = sg = sb = 255;
                }
                if (outA == 0) continue;
                var d = dst[px, py];
                int ia = 255 - outA;
                dst[px, py] = new Rgba32(
                    (byte)((sr * outA + d.R * ia) / 255),
                    (byte)((sg * outA + d.G * ia) / 255),
                    (byte)((sb * outA + d.B * ia) / 255),
                    (byte)Math.Min(255, outA + d.A * ia / 255));
            }
        }
    }

    /// <summary>The most-referenced font DID across every LayoutDesc in
    /// the local DAT — computed once per render and used when an element
    /// has text but no font property anywhere on its chain or ancestry.
    /// Data-driven so we never hardcode a DID that might differ between
    /// eras/servers.</summary>
    private uint GetDefaultFontId(UiRenderContext ctx) {
        if (ctx.DefaultFontId.HasValue) return ctx.DefaultFontId.Value;
        var counts = new Dictionary<uint, int>();
        try {
            foreach (var id in ctx.Collection.Local.GetAllIdsOfType<DRW.DBObjs.LayoutDesc>()) {
                if (!ctx.Collection.TryGet<DRW.DBObjs.LayoutDesc>(id, out var layout) || layout == null) continue;
                void Walk(DRW.Types.ElementDesc el) {
                    foreach (var sd in EnumerateStateDescs(el)) {
                        foreach (var did in EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_Fonts))) {
                            if (did != 0) counts[did] = counts.GetValueOrDefault(did) + 1;
                        }
                        foreach (var did in EnumeratePropertyUints(GetUiProperty(sd, MPID_Text_Font))) {
                            if (did != 0) counts[did] = counts.GetValueOrDefault(did) + 1;
                        }
                    }
                    if (el.Children != null) {
                        foreach (var c in el.Children.Values) Walk(c);
                    }
                }
                foreach (var root in layout.Elements.Values) Walk(root);
            }
        } catch (Exception ex) {
            ctx.Warnings.Add($"default-font scan failed: {ex.Message}");
        }
        var best = counts.OrderByDescending(k => k.Value).Select(k => k.Key).FirstOrDefault();
        if (best != 0) {
            ctx.Warnings.Add($"default font 0x{best:X8} (most-used, {counts[best]} refs) used for font-less text.");
        }
        ctx.DefaultFontId = best;
        return best;
    }

    private static IEnumerable<DRW.Types.StateDesc> EnumerateStateDescs(DRW.Types.ElementDesc el) {
        if (el.StateDesc != null) yield return el.StateDesc;
        if (el.States != null) {
            foreach (var s in el.States.Values) {
                if (s != null) yield return s;
            }
        }
    }

    // ── Property plumbing ────────────────────────────────────────────

    private static DRW.Types.BaseProperty? GetUiProperty(DRW.Types.StateDesc state, uint masterPropertyId) {
        if (state.Properties == null) return null;
        foreach (var kvp in state.Properties) {
            if (kvp.Key == masterPropertyId) return kvp.Value;
        }
        return null;
    }

    /// <summary>Flatten a property (scalar or array) into its uint-shaped
    /// values — DataId / Integer / Enum all surface here.</summary>
    private static IEnumerable<uint> EnumeratePropertyUints(DRW.Types.BaseProperty? prop) {
        if (prop == null) yield break;
        var valueField = prop.GetType().GetField("Value");
        var value = valueField?.GetValue(prop);
        if (value == null) yield break;
        var direct = ExtractMaybeUint(value);
        if (direct.HasValue) { yield return direct.Value; yield break; }
        if (value is System.Collections.IEnumerable seq && value is not string) {
            foreach (var item in seq) {
                if (item is DRW.Types.BaseProperty sub) {
                    foreach (var v in EnumeratePropertyUints(sub)) yield return v;
                } else {
                    var maybe = ExtractMaybeUint(item);
                    if (maybe.HasValue) yield return maybe.Value;
                }
            }
        }
    }

    private static IEnumerable<(byte R, byte G, byte B, byte A)> EnumeratePropertyColors(DRW.Types.BaseProperty? prop) {
        if (prop == null) yield break;
        var valueField = prop.GetType().GetField("Value");
        var value = valueField?.GetValue(prop);
        switch (value) {
            case DRW.Types.ColorARGB c:
                yield return (c.Red, c.Green, c.Blue, c.Alpha);
                break;
            case System.Collections.IEnumerable seq when value is not string: {
                foreach (var item in seq) {
                    if (item is DRW.Types.BaseProperty sub) {
                        foreach (var c in EnumeratePropertyColors(sub)) yield return c;
                    } else if (item is DRW.Types.ColorARGB c2) {
                        yield return (c2.Red, c2.Green, c2.Blue, c2.Alpha);
                    }
                }
                break;
            }
        }
    }

    private string? ResolveStringInfoProperty(UiRenderContext ctx, DRW.Types.BaseProperty? prop) {
        if (prop == null) return null;
        var valueField = prop.GetType().GetField("Value");
        if (valueField?.GetValue(prop) is not DRW.Types.StringInfo si) return null;
        // TableId is a QualifiedDataId<StringTable> — resolve through the
        // collection (routes to the local DAT where StringTables live).
        var table = si.TableId.Get(ctx.Collection);
        if (table == null) {
            ctx.Warnings.Add($"StringTable {si.TableId} not found (string 0x{si.StringId:X8}).");
            return null;
        }
        if (!table.Strings.TryGetValue(si.StringId, out var sts) || sts == null || sts.Strings.Count == 0) {
            ctx.Warnings.Add($"String 0x{si.StringId:X8} not in StringTable {si.TableId}.");
            return null;
        }
        string s = sts.Strings[0];
        return s?.Replace("\\n", "\n");
    }

    private static string Truncate(string s, int n) => s.Length <= n ? s : s.Substring(0, n) + "…";

    // ─────────────────────────────────────────────────────────────────
    //  ui-element-edit
    // ─────────────────────────────────────────────────────────────────

    public sealed record UiElementEditSpec(
        uint ElementId, uint? X, uint? Y, uint? Width, uint? Height, uint? ZLevel);

    public UiElementEditResult UiElementEdit(
        string datPath, uint layoutId, IReadOnlyList<UiElementEditSpec> edits, bool dryRun) {
        if (edits == null || edits.Count == 0) {
            throw new ArgumentException("edits array is required and must be non-empty.");
        }
        var resolved = Path.GetFullPath(GuardWritableDatCopy(datPath));

        // Read through a full collection so BaseProperty.UnpackGeneric can
        // resolve the portal MasterProperty (same wiring as the dump
        // command); the LOCAL side reads from the caller's copy.
        DRW.DBObjs.LayoutDesc layout;
        {
            var portal = ResolveDatPathOrAlias(null, defaultAlias: "portal");
            var opts = new DRW.Options.DatCollectionOptions {
                DatDirectory = Path.GetDirectoryName(resolved)!,
                AccessType = DRW.Options.DatAccessType.Read,
                LocalDatPath = resolved,
                PortalDatPath = portal,
                HighResDatPath = portal,
                CellDatPath = ResolveDatPathOrAlias(null, defaultAlias: "cell"),
            };
            using var collection = new DRW.DatCollection(opts);
            if (!collection.TryGet<DRW.DBObjs.LayoutDesc>(layoutId, out var l) || l == null) {
                throw new InvalidOperationException($"LayoutDesc 0x{layoutId:X8} not found in {resolved}.");
            }
            layout = l;
        }

        var reports = new List<Dictionary<string, object?>>();
        int applied = 0;
        foreach (var edit in edits) {
            var el = FindElementDeep(layout, edit.ElementId);
            var rep = new Dictionary<string, object?> {
                ["elementIdHex"] = $"0x{edit.ElementId:X8}",
                ["found"] = el != null,
            };
            if (el != null) {
                rep["before"] = new { x = el.X, y = el.Y, width = el.Width, height = el.Height, zLevel = el.ZLevel };
                if (edit.X.HasValue) el.X = edit.X.Value;
                if (edit.Y.HasValue) el.Y = edit.Y.Value;
                if (edit.Width.HasValue) el.Width = edit.Width.Value;
                if (edit.Height.HasValue) el.Height = edit.Height.Value;
                if (edit.ZLevel.HasValue) el.ZLevel = edit.ZLevel.Value;
                rep["after"] = new { x = el.X, y = el.Y, width = el.Width, height = el.Height, zLevel = el.ZLevel };
                applied++;
            }
            reports.Add(rep);
        }

        bool written = false;
        if (!dryRun && applied > 0) {
            // Write through a dedicated ReadWrite handle. Pack() has no
            // MasterProperty dependency (verified against 2.1.2 — only
            // UnpackGeneric reaches the collection), so a bare
            // LocalDatabase suffices.
            using var rw = new DRW.LocalDatabase(resolved, DRW.Options.DatAccessType.ReadWrite);
            var result = rw.TryWriteFile(layout);
            if (!result.Success) {
                throw new InvalidOperationException($"TryWriteFile failed: {result.Error}");
            }
            written = true;
        }

        return new UiElementEditResult(
            DatPath: resolved,
            LayoutIdHex: $"0x{layoutId:X8}",
            DryRun: dryRun,
            Written: written,
            Edits: reports);
    }

    private static DRW.Types.ElementDesc? FindElementDeep(DRW.DBObjs.LayoutDesc layout, uint elementId) {
        DRW.Types.ElementDesc? Find(DRW.Types.ElementDesc el) {
            if (el.ElementId == elementId) return el;
            if (el.Children != null) {
                foreach (var c in el.Children.Values) {
                    var hit = Find(c);
                    if (hit != null) return hit;
                }
            }
            return null;
        }
        foreach (var root in layout.Elements.Values) {
            var hit = Find(root);
            if (hit != null) return hit;
        }
        return null;
    }

    /// <summary>Writable-copy guard shared by the two write commands:
    /// the path must exist and must NOT live under ~/ac_base_dats (the
    /// pristine bake inputs are never written — point the command at a
    /// copy).</summary>
    private static string GuardWritableDatCopy(string datPath) {
        if (string.IsNullOrWhiteSpace(datPath)) {
            throw new ArgumentException(
                "datPath is required for write commands and must point at a DAT COPY (never ~/ac_base_dats).");
        }
        var full = Path.GetFullPath(datPath.Trim());
        if (!File.Exists(full)) {
            throw new FileNotFoundException($"datPath not found: {full}");
        }
        var baseDats = Path.GetFullPath(Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "ac_base_dats"));
        if (full.StartsWith(baseDats + Path.DirectorySeparatorChar, StringComparison.Ordinal)
            || full.Equals(baseDats, StringComparison.Ordinal)) {
            throw new InvalidOperationException(
                $"Refusing to write into ~/ac_base_dats ({full}) — copy the DAT elsewhere first (base DATs stay pristine).");
        }
        return full;
    }

    // ─────────────────────────────────────────────────────────────────
    //  ui-image-replace
    // ─────────────────────────────────────────────────────────────────

    public sealed record UiImageReplaceSpec(uint Did, string PngPath);

    public UiImageReplaceResult UiImageReplace(
        string datPath, IReadOnlyList<UiImageReplaceSpec> replacements,
        bool dryRun, bool allowCreate) {
        if (replacements == null || replacements.Count == 0) {
            throw new ArgumentException(
                "No replacements resolved — pass a 'replacements' array or a 'fromDir' of 0x06XXXXXX.png files.");
        }
        var resolved = GuardWritableDatCopy(datPath);

        var records = new List<Dictionary<string, object?>>();
        int written = 0, failed = 0;

        using var portal = new DRW.PortalDatabase(resolved,
            dryRun ? DRW.Options.DatAccessType.Read : DRW.Options.DatAccessType.ReadWrite);

        foreach (var spec in replacements) {
            var rec = new Dictionary<string, object?> {
                ["didHex"] = $"0x{spec.Did:X8}",
                ["pngPath"] = spec.PngPath,
            };
            try {
                if (!File.Exists(spec.PngPath)) {
                    throw new FileNotFoundException($"png not found: {spec.PngPath}");
                }
                portal.TryGet<DRW.DBObjs.RenderSurface>(spec.Did, out var existing);
                if (existing == null && !allowCreate) {
                    throw new InvalidOperationException(
                        $"RenderSurface 0x{spec.Did:X8} not present in {Path.GetFileName(resolved)} " +
                        "(pass allowCreate=true to add a new record).");
                }

                using var img = Image.Load<Rgba32>(spec.PngPath);
                bool opaque = true;
                img.ProcessPixelRows(acc => {
                    for (int y = 0; y < acc.Height && opaque; y++) {
                        var row = acc.GetRowSpan(y);
                        for (int x = 0; x < row.Length; x++) {
                            if (row[x].A != 255) { opaque = false; break; }
                        }
                    }
                });

                // Format policy: keep R8G8B8 for opaque replacements of
                // R8G8B8 originals (byte layout BGR — the repo-wide trap
                // documented in RenderSurfaceExtensions); everything else
                // becomes A8R8G8B8 (BGRA). Palette/DXT/JPEG originals are
                // re-encoded — retail reads the per-record format field,
                // so mixed formats in one DAT are fine.
                var srcFormat = existing?.Format;
                bool asRgb = srcFormat == DRW.Enums.PixelFormat.PFID_R8G8B8 && opaque;
                byte[] data;
                if (asRgb) {
                    data = new byte[img.Width * img.Height * 3];
                    for (int y = 0; y < img.Height; y++)
                    for (int x = 0; x < img.Width; x++) {
                        var p = img[x, y];
                        int i = (y * img.Width + x) * 3;
                        data[i + 0] = p.B; data[i + 1] = p.G; data[i + 2] = p.R;
                    }
                } else {
                    data = new byte[img.Width * img.Height * 4];
                    for (int y = 0; y < img.Height; y++)
                    for (int x = 0; x < img.Width; x++) {
                        var p = img[x, y];
                        int i = (y * img.Width + x) * 4;
                        data[i + 0] = p.B; data[i + 1] = p.G; data[i + 2] = p.R; data[i + 3] = p.A;
                    }
                }

                var surface = new DRW.DBObjs.RenderSurface {
                    Id = spec.Did,
                    Width = img.Width,
                    Height = img.Height,
                    Format = asRgb ? DRW.Enums.PixelFormat.PFID_R8G8B8 : DRW.Enums.PixelFormat.PFID_A8R8G8B8,
                    DefaultPaletteId = existing?.DefaultPaletteId ?? 0,
                    SourceData = data,
                };

                rec["srcFormat"] = srcFormat?.ToString() ?? "(new)";
                rec["dstFormat"] = surface.Format.ToString();
                rec["width"] = img.Width;
                rec["height"] = img.Height;
                rec["bytes"] = data.Length;

                if (!dryRun) {
                    var result = portal.TryWriteFile(surface);
                    if (!result.Success) {
                        throw new InvalidOperationException($"TryWriteFile failed: {result.Error}");
                    }
                }
                rec["status"] = dryRun ? "DRY-RUN" : "WRITTEN";
                written++;
            } catch (Exception ex) {
                rec["status"] = "FAIL";
                rec["error"] = ex.Message;
                failed++;
            }
            records.Add(rec);
        }

        return new UiImageReplaceResult(
            DatPath: resolved, DryRun: dryRun,
            RequestedCount: replacements.Count,
            WrittenCount: dryRun ? 0 : written,
            FailCount: failed,
            Records: records);
    }

    // ─────────────────────────────────────────────────────────────────
    //  ui-pack-export
    // ─────────────────────────────────────────────────────────────────

    public UiPackExportResult UiPackExport(
        string outDir, IReadOnlyList<uint>? layoutIds, string? datPath, bool includeImages) {
        if (string.IsNullOrWhiteSpace(outDir)) {
            throw new ArgumentException("outDir is required.");
        }
        Directory.CreateDirectory(outDir);

        using var collection = OpenUiCollectionRead(datPath);

        var ids = (layoutIds != null && layoutIds.Count > 0)
            ? layoutIds.Distinct().OrderBy(i => i).ToList()
            : collection.Local.GetAllIdsOfType<DRW.DBObjs.LayoutDesc>().OrderBy(i => i).ToList();

        var panels = new List<Dictionary<string, object?>>();
        // image key → usage aggregation
        var imageUsage = new Dictionary<(uint ImageId, uint AlphaId), (SortedSet<string> Panels, List<Dictionary<string, object?>> Nodes)>();
        int nodeTotal = 0;
        var skipped = new List<Dictionary<string, object?>>();

        foreach (var layoutId in ids) {
            if (!collection.TryGet<DRW.DBObjs.LayoutDesc>(layoutId, out var layout) || layout == null) {
                skipped.Add(new Dictionary<string, object?> {
                    ["layout_id"] = layoutId, ["reason"] = "LayoutDesc not found",
                });
                continue;
            }
            var firstRoot = layout.Elements.Values.OrderBy(e => e.ReadOrder).FirstOrDefault();
            var rootName = firstRoot != null ? TryResolveUiElementIdName(firstRoot.ElementId) : null;
            var slug = MakePanelSlug(rootName, layoutId);

            var nodes = new List<Dictionary<string, object?>>();
            int traversal = 0;

            void WalkNode(DRW.Types.ElementDesc el, int? parentTraversal, int parentAbsX, int parentAbsY) {
                int myIndex = traversal++;
                int absX = parentAbsX + (int)el.X;
                int absY = parentAbsY + (int)el.Y;

                var (defaultImage, states) = ExtractStateImages(el);
                var kind = ClassifyWidgetKind(el, defaultImage != null || states.Count > 0);

                nodes.Add(new Dictionary<string, object?> {
                    ["traversal_index"] = myIndex,
                    ["element_id"] = el.ElementId,
                    ["layout_id"] = layoutId,
                    ["parent_layout_id"] = parentTraversal.HasValue ? layoutId : (uint?)null,
                    ["parent_traversal_index"] = parentTraversal,
                    ["base_layout_id"] = el.BaseLayoutId,
                    ["rect"] = new Dictionary<string, object?> {
                        ["x"] = (float)absX, ["y"] = (float)absY,
                        ["width"] = (float)el.Width, ["height"] = (float)el.Height,
                    },
                    ["widget_kind"] = kind,
                    ["state_set"] = new Dictionary<string, object?> {
                        ["default_image"] = defaultImage,
                        ["states"] = states,
                    },
                });

                void Record(Dictionary<string, object?>? imageKey, uint? stateId) {
                    if (imageKey == null) return;
                    var key = ((uint)(imageKey["image_id"] ?? 0u),
                               (uint)(imageKey["alpha_image_id"] ?? 0u));
                    if (!imageUsage.TryGetValue(key, out var agg)) {
                        agg = (new SortedSet<string>(StringComparer.Ordinal), new List<Dictionary<string, object?>>());
                        imageUsage[key] = agg;
                    }
                    agg.Panels.Add(slug);
                    agg.Nodes.Add(new Dictionary<string, object?> {
                        ["panel_slug"] = slug,
                        ["traversal_index"] = myIndex,
                        ["element_id"] = el.ElementId,
                        ["state_id"] = stateId,
                    });
                }
                Record(defaultImage, null);
                foreach (var s in states) {
                    Record(s["image"] as Dictionary<string, object?>, (uint?)(s["state_id"] as uint?));
                }

                if (el.Children != null) {
                    foreach (var c in el.Children.Values.OrderBy(e => e.ReadOrder).ThenBy(e => e.ElementId)) {
                        WalkNode(c, myIndex, absX, absY);
                    }
                }
            }

            foreach (var root in layout.Elements.Values.OrderBy(e => e.ReadOrder).ThenBy(e => e.ElementId)) {
                WalkNode(root, null, 0, 0);
            }
            nodeTotal += nodes.Count;

            panels.Add(new Dictionary<string, object?> {
                ["id"] = firstRoot?.ElementId ?? layoutId,
                ["slug"] = slug,
                ["title"] = MakePanelTitle(rootName, layoutId),
                ["bucket"] = "Exported",
                ["parent_slug"] = null,
                ["width"] = layout.Width,
                ["height"] = layout.Height,
                ["nodes"] = nodes,
            });
        }

        // images[] — decode dims + optionally extract PNGs via the
        // existing extractor (which also writes its INDEX.json).
        string? imagesDir = null;
        int pngPass = 0, pngFail = 0;
        var allDids = imageUsage.Keys
            .SelectMany(k => new[] { k.ImageId, k.AlphaId })
            .Where(d => d != 0).Distinct().OrderBy(d => d).ToList();
        var dimsByDid = new Dictionary<uint, (int W, int H)>();
        if (includeImages && allDids.Count > 0) {
            imagesDir = Path.Combine(outDir, "images");
            var extract = ChoriziteExtractUiTextures(allDids, imagesDir, datPath: null);
            pngPass = extract.PngCount;
            pngFail = extract.FailCount;
            foreach (var r in extract.Records) {
                if (r.Status == "PASS") dimsByDid[r.Did] = (r.Width, r.Height);
            }
        }

        var images = new List<Dictionary<string, object?>>();
        foreach (var kvp in imageUsage.OrderBy(k => k.Key.ImageId).ThenBy(k => k.Key.AlphaId)) {
            dimsByDid.TryGetValue(kvp.Key.ImageId, out var dims);
            images.Add(new Dictionary<string, object?> {
                ["key"] = new Dictionary<string, object?> {
                    ["image_id"] = kvp.Key.ImageId,
                    ["alpha_image_id"] = kvp.Key.AlphaId == 0 ? null : (uint?)kvp.Key.AlphaId,
                },
                ["relative_path"] = $"images/0x{kvp.Key.ImageId:X8}.png",
                ["width"] = dims.W,
                ["height"] = dims.H,
                ["used_by_panels"] = kvp.Value.Panels.ToList(),
                ["used_by_nodes"] = kvp.Value.Nodes,
            });
        }

        var pack = new Dictionary<string, object?> {
            ["version"] = 1,
            ["panels"] = panels,
            ["images"] = images,
            ["skipped_panels"] = skipped,
        };
        var packJsonPath = Path.Combine(outDir, "reference_pack.json");
        File.WriteAllText(packJsonPath, JsonSerializer.Serialize(pack,
            new JsonSerializerOptions { WriteIndented = true }));

        return new UiPackExportResult(
            OutDir: Path.GetFullPath(outDir),
            PackJsonPath: Path.GetFullPath(packJsonPath),
            PanelCount: panels.Count,
            NodeCount: nodeTotal,
            ImageCount: images.Count,
            PngPass: pngPass,
            PngFail: pngFail,
            ImagesDir: imagesDir != null ? Path.GetFullPath(imagesDir) : null);
    }

    /// <summary>default_image + per-state image keys for one element —
    /// first Image media of a StateDesc, paired with an Alpha media in
    /// the same state (the pack's {image_id, alpha_image_id} shape).</summary>
    private static (Dictionary<string, object?>? DefaultImage, List<Dictionary<string, object?>> States)
        ExtractStateImages(DRW.Types.ElementDesc el) {

        static Dictionary<string, object?>? FirstImageKey(DRW.Types.StateDesc? s) {
            if (s?.Media == null) return null;
            uint image = 0, alpha = 0;
            foreach (var m in s.Media) {
                if (image == 0 && m is DRW.Types.MediaDescImage i) image = i.File;
                if (alpha == 0 && m is DRW.Types.MediaDescAlpha a) alpha = a.File;
            }
            if (image == 0) return null;
            return new Dictionary<string, object?> {
                ["image_id"] = image,
                ["alpha_image_id"] = alpha == 0 ? null : (uint?)alpha,
            };
        }

        var def = FirstImageKey(el.StateDesc);
        var states = new List<Dictionary<string, object?>>();
        if (el.States != null) {
            foreach (var kvp in el.States.OrderBy(k => (uint)k.Key)) {
                var key = FirstImageKey(kvp.Value);
                if (key == null) continue;
                states.Add(new Dictionary<string, object?> {
                    ["state_id"] = (uint)kvp.Key,
                    ["image"] = key,
                });
            }
        }
        return (def, states);
    }

    /// <summary>Best-effort widget classification mirroring the Rust
    /// pack's vocabulary {Group, Sprite, Button, Scrollbar, Slider} from
    /// the retail element Type (ACElementType: Button=1, Dragbar=2,
    /// Meter=7, Scrollbar=11 per the reference app's enum).</summary>
    private static string ClassifyWidgetKind(DRW.Types.ElementDesc el, bool hasImage) {
        return el.Type switch {
            1 => "Button",
            11 => "Scrollbar",
            2 or 7 => "Slider",
            _ => hasImage ? "Sprite" : "Group",
        };
    }

    private static string MakePanelSlug(string? rootName, uint layoutId) {
        if (!string.IsNullOrEmpty(rootName)) {
            var s = rootName;
            if (s.StartsWith("Root", StringComparison.Ordinal)) s = s.Substring(4);
            if (s.EndsWith("_Field", StringComparison.Ordinal)) s = s.Substring(0, s.Length - 6);
            s = string.Concat(s.Select((c, i) =>
                char.IsUpper(c) && i > 0 && !char.IsUpper(s[i - 1]) ? "_" + char.ToLowerInvariant(c) : char.ToLowerInvariant(c).ToString()));
            s = s.Replace("__", "_").Trim('_');
            if (s.Length > 0) return s;
        }
        return $"layout_{layoutId:x8}";
    }

    private static string MakePanelTitle(string? rootName, uint layoutId) {
        var slug = MakePanelSlug(rootName, layoutId);
        return string.Join(" ", slug.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => w.Length > 0 ? char.ToUpperInvariant(w[0]) + w.Substring(1) : w));
    }

    // ─────────────────────────────────────────────────────────────────
    //  Shared collection opener — local+portal with the HighRes→portal
    //  trick (same wiring as ChoriziteDumpLayoutTree; see that command's
    //  comment for why the collection is load-bearing for BaseProperty
    //  unpacking).
    // ─────────────────────────────────────────────────────────────────

    private DRW.DatCollection OpenUiCollectionRead(string? localDatPath) {
        var resolvedLocal = ResolveDatPathOrAlias(localDatPath, defaultAlias: "local");
        var resolvedPortal = ResolveDatPathOrAlias(null, defaultAlias: "portal");
        var opts = new DRW.Options.DatCollectionOptions {
            DatDirectory = Path.GetDirectoryName(resolvedLocal)!,
            AccessType = DRW.Options.DatAccessType.Read,
            LocalDatPath = resolvedLocal,
            PortalDatPath = resolvedPortal,
            HighResDatPath = resolvedPortal,
            CellDatPath = ResolveDatPathOrAlias(null, defaultAlias: "cell"),
        };
        return new DRW.DatCollection(opts);
    }
}
