<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\WorldBuilder\WorldBuilder.csproj" />
        <ProjectReference Include="..\WorldBuilder.Shared\WorldBuilder.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.9" />
    </ItemGroup>
</Project>
